bind = SUPER, Q, killactive
bind = SUPER, Return, exec, kitty
bind = SUPER, F, exec, firefox
bind = SUPER, D, exec, wofi --show drun
bind = SUPER SHIFT, R, exec, hyprctl reload
bind = SUPER SHIFT, Q, exit
bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png
